#database.yml

development_adapter : mysql
development_database : lf_prod
development_username : root
development_password : mysqlbpi
development_host : 10.1.2.113

test_adapter : mysql
test_database : lf_test
test_username : root
test_password : bpi
test_host : localhost

production_adapter : mysql
production_database : lf_prod
production_username : root
production_password : mysqlbpi
production_host : 10.1.2.113

#config.yml

libraryfind_indexer : solr
libraryfind_ferret_path : 

libraryfind_solr_host : 'http://10.1.2.113:8080/solr'
libraryfind_solr_harvesting_url : 'http://10.1.2.157:8080/solr'

memcached_servers: '127.0.0.1,10.1.2.111:11211,10.1.2.112:11211,10.1.2.113:11211'

FREE_ACCESS_GROUPS: 'GD-Articles de presse,GD-Ged,GD-Journaux en ligne,GD-Mezzanine,GD-Réel,GD-Tous secteurs'

nb_resultat_max : 10
max_collection_search : 25

parser_type : nokogiri
language : FR
languages : FR,EN,ES
defautl_groups :  a_tout_generalites
general_template : general
images_template : images

ill_url : 'https://yourlibrary.edu/illiad.dll/OpenURL?'

openlibrary_covers : 1

GED_URL_SEPARATOR: '/'
GED_URL_PATH: 'http://sged.ck.bpi.fr/BPI/'
GED_NB_CAR_REP: 8
GED_NAME_FILE: 'GED.pdf'

CFG_LF_URL_BASE: "http://10.1.2.111/"
CFG_LF_TIMEOUT: 30
CFG_LF_TIMEOUT_SOLR: 300

SMTP_ADRESS: 129.102.240.245
SMTP_PORT: 25
SMTP_DOMAIN: bpi.fr
SMTP_LOGIN: 
SMTP_PWD: 
SMTP_MAIL_EMETTEUR: 'no-reply@bpi.fr'

LINK_SATISFACTION_URL: 'http://a_modifier.fr'
LINK_MESSAGERIE_URL: 'http://a_modifier.fr'

WIDGET_SETS: 'g6'

SEE_ALSO_ACTIVATE: '1'
SEE_ALSO_MAX: 15
SYNONYMS_FILE_INPUT: '/srv/libraryfind/components/synonymes/synonyms.csv'
SYNONYMS_FILE_OUTPUT_SOLR: '/srv/libraryfind/components/synonymes/synonyms.txt'
SYNONYMS_SEPARATOR_MULTI_VALUES: '@;@'
SYNONYMS_SEPARATOR_CSV: ';"'

SPELL_ACTIVATE: '1'
COUNT: 5

LOG_FILE_LOCATION: '/srv/stats/'
LOG_NAME_FILE: 'log_statistic_bpi.log'

AMD64: 0

#webservice.yml

ws_username : 'eldemows'
ws_password : 'ur76Pu73'

proxy_http_adr : ''
proxy_http_port : 0
proxy_http_login : ''
proxy_http_pwd : ''

#ranking.yml

special_boost : 100
pref : 50000

title_perfect_match : 10000
title_partial_match : 2000
title_partial_match_offset_1 : 500
title_partial_match_offset_up : 300

creator_perfect_match : 5000
creator_partial_match : 1000
creator_partial_match_offset_1 : 300 
creator_partial_match_offset_sup : 75

subject_perfect_match : 5000
subject_partial_match_offset_1 : 300
subject_partial_match_offset_sup : 75

theme_perfect_match : 5000
theme_partial_match : 2000

indice_perfect_match : 5000
indice_partial_match : 2000
indice_partial_match_offset_1 : 500
indice_partial_match_offset_sup : 300

DATE_BOOST : 1000
CATALOGUE_BPI_BOOST : 3000
PORTFOLIO_REVUE_BOOST : 7000

TITLE_SOLR_MATCH : 10000
CREATOR_SOLR_MATCH : 5000
SUBJECT_SOLR_MATCH : 5000
THEME_SOLR_MATCH : 5000
INDICE_SOLR_MATCH : 5000

TITLE_SOLR_MATCH_EXACT : 5000
CREATOR_SOLR_MATCH_EXACT : 2500
SUBJECT_SOLR_MATCH_EXACT : 2500
THEME_SOLR_MATCH_EXACT : 2500

